### PR TITLE
Leap motion integration

### PR DESCRIPTION
**Pull request by lmikaellukerad**
Grab script for leap motion and testing tools included.

### CODE REVIEW

**Comment by lmikaellukerad** [comment]
Passes unity cloud build

**Comment by lmikaellukerad** [comment]
Now mergeable with master

**Comment by GitHubJasper** [comment]
Nice, good we use cloud build!

**Comment by GitHubJasper** [comment]
gg wp

**Comment by arjanvanschendel** [comment]
Looks good, well done!
(wp 4Head)

**Pull request merged**
