### PR TITLE
Manus vr integration

### PR DESCRIPTION
**Pull request by arjanvanschendel**
Addition of manusVR integration, leap+manusVR added to supermarket scene

### CODE REVIEW

**Comment by mtavasszy** [comment]
looks good!

**Comment by lmikaellukerad** [comment]
needs more unit test Kappa

**Comment by GitHubJasper** [comment]
Nice, I see you added test for the Manus as wel! Great!

**Comment by bartziengs** [comment]
Art is the imposing of a pattern on experience, and your aesthetic enjoyment is recognition of the pattern. gg wp m8

**Pull request merged**
