### PR TITLE
Vibration

### PR DESCRIPTION
**Pull request by arjanvanschendel**
Added class for vibration. Left glove can now start vibrating by pressing n, stop vibrating by pressing m, or vibrate shortly by pressing b. The methods can be called from outside the class, and are therefore useful for collision detection feedback.

### CODE REVIEW

**Comment by GitHubJasper** [comment]
Arjans private vibrator script

**Comment by arjanvanschendel** [comment]
public class ManusVibrate : MonoBehaviour 

Not even private ( ͡° ͜ʖ ͡°)

**Comment by mtavasszy** [comment]
stock-photo-positive-vibration-word-write-on-white-background-by-woman-hand-holding-highlighter-pen-362817200

**Pull request merged**
