### PR TITLE
Comments

### PR DESCRIPTION
**Pull request by mtavasszy**
Comments and code style improvements according to GhostDoc and StyleCop

### CODE REVIEW

**Comment by arjanvanschendel** [comment]
screenshot_2

**Comment by lmikaellukerad** [comment]
ive merged my stylecop proof scripts

**Comment by mtavasszy** [comment]
Thanks

**Comment by GitHubJasper** [comment]
Great! We should have done this from the start

**Comment by bartziengs** [comment]
Nice work, looks very clear

**Pull request merged**
