### PR TITLE
Vibration

### PR DESCRIPTION
**Pull request by arjanvanschendel**
Slight tweaks in vibration duration, minor bugfixes.

### CODE REVIEW

**Comment by lmikaellukerad** [comment]
A shocking feature for sure

**Comment by mtavasszy** [comment]
added double double vibration

MERGE

**Comment by GitHubJasper** [comment]
A trilling new feature

**Comment by bartziengs** [comment]
I'm t(h)rilled

**Comment by arjanvanschendel** [comment]
Nice Bart, stealing jokes. 

I'll merge before this gets out of manus(VR).

**Pull request merged**
