### PR TITLE
Shopping cart

### PR DESCRIPTION
**Pull request by mtavasszy**
Added a shopping cart. Can move around and have items thrown in/ taken out. Fully tested

### CODE REVIEW

**Comment by lmikaellukerad** [comment]
# CONFLICTS
## CONFLICTS
### CONFLICTS
#### CONFLICTS
##### CONFLICTS

**Comment by mtavasszy** [comment]
Ready to merge!

**Comment by bartziengs** [comment]
toppie ouwe, kan die wachten om met dat wagentje te rollen

**Pull request merged**
